language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql
  - postgresql

env:
  - DB=mysql RUNLEVEL=0
  - DB=mysql RUNLEVEL=10
  - DB=pgsql RUNLEVEL=0
  - DB=pgsql RUNLEVEL=10

matrix:
    allow_failures:
        - php: 7.2

before_script:
  - composer selfupdate --no-progress
  - travis_retry composer install --prefer-dist
  - mkdir tests/_temp
  - "sh -c \"if [ '$DB' = 'mysql' ]; then cp tests/_helpers/mysql.neon tests/tests.local.neon; fi\""
  - "sh -c \"if [ '$DB' = 'pgsql' ]; then cp tests/_helpers/pgsql.neon tests/tests.local.neon; fi\""

script:
  - src/run-tests --bootstrap tests/bootstrap.php

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

notifications:
  email: false
